### ISSUE TITLE
Rough Overarching Accounting Model

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/RevolvingLoanHack#13]
System Needs Continuous Statements of: 
# Assets
# Liabilities
# Equity
# Income
# Expenses

*\* See NCUA combined statement example below, also at:
- https://www.ncua.gov/Resources/Documents/CUDev/CDRLF200712Statement.pdf 

![screen shot 2016-10-16 at 1 41 54 am](https://cloud.githubusercontent.com/assets/2357755/19415560/e07c7c50-9341-11e6-9dc9-bcee093eddaa.png)

**Also Need**
# Continuous Ledger Entry System for All Transactions

**Comment by prhana** [comment]
https://github.com/HumanDynamics/RevolvingLoanHack/edit/master/ProjectPlan/Accounting/README.md DONE!
