### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by i143code** [HumanDynamics/RevolvingLoanHack#2]
Hash generated : a5bc16e55c20ed52b361a8134cf2ff31
hash
{"firstname":"firstname","lastname":"lastname","emailaddress":"emailaddress@gmail.com","address":"address","optionsradios":"option1"}

**Comment by dazzaji** [comment]
Cool - I'll rehash it to confirm. Can you add the file(s) and line(s) where you invoke the hash and store the resulting message digest that is passed to Wayne's company?
