### ISSUE TITLE
Updates to Ruby on Rails code

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/RevolvingLoanHack#5]
For code deployed originating from this repo to : https://obscure-hamlet-99782.herokuapp.com/users/sign_in
- Please update copyright on all pages to give you credit but share under creative commons.

Replace this: "© Company Ashish Ranjan"

With this: "© Ashish Ranjan, Licensed under Creative Commons Attribution License"

**Comment by dazzaji** [comment]
Also, please fix typo on "Agree" button on loan application

Also: please move "use current card" to top of payment page

**Comment by prhana** [comment]
Please add: https://github.com/HumanDynamics/RevolvingLoanHack/blob/master/RLH-WebPhoto.jpg

**Comment by dazzaji** [comment]
done!
